### ISSUE TITLE
Unexpected behavior with tabbed code

### ISSUE THREAD

**Issue by mathuin** [christophergandrud/language-knitr#5]
When I use LaTeX, I indent inside begins, like so:

```
\begin{document}
    <<first-method-setup, include=FALSE>>=
    options(scipen = 5, digits = 4)
    knit_hooks$set(document = function(x) {
        sub('\\usepackage[]{color}',
            '\\usepackage{xcolor}', x, fixed = TRUE)
            }) # $
    opts_knit$set(self.contained = TRUE, width = 55) # $
    source("first-setup.R")
    @
```

When `language-knitr` sees this code, I get a purple(?) reverse video bar over the `<<...>>=` line and the R code is formatted like LaTeX (which is why I have the `# $`).  When I unindent the code, I get what I think is proper highlighting -- no more purple bar and appropriate coloring of the R code.  Is there a way to make the highlighting work when the code is indented?

**Comment by christophergandrud** [comment]
Sorry, I don't really support this package anymore. (I've converted over to RMarkdown for pretty much everything).

That being said, I would consider a pull request to https://github.com/christophergandrud/language-knitr/blob/master/grammars/knitr.cson

**Comment by mathuin** [comment]
Challenge accepted!
